expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-tls

externalURL: https://core.harbor.domain
harborAdminPassword: Harbor12345

persistence:
  enabled: false # For local testing

portal:
  service:
    type: ClusterIP
