apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    logs:
      general:
        level: INFO
      access:
        enabled: true

    ports:
      web:
        expose:
          default: true
      websecure:
        expose:
          default: true

    ingressRoute:
      dashboard:
        enabled: true
